-- PAIR PROGRAMMING LECCION 3: ALTERACION DE TABLAS

-- INTRODUCIR MARCA Y TALLA EN LA TABLA ZAPATILLAS
ALTER TABLE zapatillas
	ADD COLUMN marca VARCHAR(45) NOT NULL,
    ADD COLUMN talla INT NOT NULL;
    
-- CAMBIAR TIPO DE DATO A DECIMAL
ALTER TABLE empleados
	 MODIFY COLUMN salario FLOAT NOT NULL;

-- ELIMINAR COLUMNA DE PAIS DE LA TABLA DE CLIENTES
ALTER TABLE clientes
	DROP COLUMN pais;

-- CAMBIAR TIPO DE DATO DE STRING A INTEGER
ALTER TABLE clientes
	MODIFY COLUMN codigo_postal INT(5);

-- CREAR COLUMNA DE TOTAL
ALTER TABLE facturas
	ADD COLUMN total FLOAT;
	